name: Enforce Merging Rules
on: [pull_request]

jobs:
  job:
    name: Applying Rules
    runs-on: ubuntu-latest
    steps:
      - name: Branch checks
        run: |
          case $GITHUB_HEAD_REF in
          "feature/"*)
              if [[ ! ( "$GITHUB_BASE_REF" == "develop" ) ]]; 
              then 
                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
                  exit 2
              fi
          ;;
          "release/"*)
              if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
              then 
                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
                  exit 2
              fi
          ;;
          "hotfix/"*)
              if [[ ! ( "$GITHUB_BASE_REF" == "develop" || "$GITHUB_BASE_REF" == "main" ) ]]; 
              then 
                  echo "The $GITHUB_HEAD_REF branch is not mergeable to $GITHUB_BASE_REF"
                  exit 2
              fi
          ;;
          *)
              echo "The branch $GITHUB_HEAD_REF cannot be merged to the branch $GITHUB_BASE_REF "
              exit 2
          esac
